<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>

		<ApplicationManifest>app.manifest</ApplicationManifest>
		<ApplicationIcon>wpfui-icon.ico</ApplicationIcon>

		<UseWPF>true</UseWPF>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>

		<!-- 单文件发布 -->
		<PublishSingleFile>true</PublishSingleFile>

		<!-- 自带 .NET 运行库 -->
		<SelfContained>true</SelfContained>

		<!-- Windows 64位 -->
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>

		<!-- WPF 不建议裁剪 -->
		<PublishTrimmed>false</PublishTrimmed>
	
	    <!-- Native DLL 自动释放到 AppData -->
	    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
	</PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\qvertionmiku.ico" />
    <EmbeddedResource Include="playAssets\2025\BodycamLocalization_P.pak">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="playAssets\2025\BodycamLocalization_P.utoc">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="playAssets\2026\AruiAndmetaOBS\BodycamLocalization_P.ucas">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="playAssets\2026\AruiAndmetaOBS\BodycamLocalization_P.utoc">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="playAssets\2026\BodycamLocalization_P.pak">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="playAssets\2026\BodycamLocalization_P.utoc">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <Content Include="app.ico" />
    <Content Include="wpfui-icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3856.49" />
    <PackageReference Include="WPF-UI" Version="4.2.0" />
    <PackageReference Include="WPF-UI.DependencyInjection" Version="4.2.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.1" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0 " />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Assets\app.ico" />
    <None Remove="Assets\bodycambackg.jpg" />
    <None Remove="Assets\bodycamsteam.jpg" />
    <None Remove="Assets\qvertionmiku.ico" />
    <None Remove="Assets\wpfui-icon-256.png" />
    <None Remove="Assets\wpfui-icon-1024.png" />
    <None Remove="playAssets\2025\BodycamLocalization_P.pak" />
    <None Remove="playAssets\2025\BodycamLocalization_P.ucas" />
    <None Remove="playAssets\2025\BodycamLocalization_P.utoc" />
    <None Remove="playAssets\2026\AruiAndmetaOBS\BodycamLocalization_P.pak" />
    <None Remove="playAssets\2026\AruiAndmetaOBS\BodycamLocalization_P.ucas" />
    <None Remove="playAssets\2026\AruiAndmetaOBS\BodycamLocalization_P.utoc" />
    <None Remove="playAssets\2026\BodycamLocalization_P.pak" />
    <None Remove="playAssets\2026\BodycamLocalization_P.ucas" />
    <None Remove="playAssets\2026\BodycamLocalization_P.utoc" />
    <None Remove="playAssets\2026\patch\BodycamLocalization_P.pak" />
    <None Remove="playAssets\2026\patch\BodycamLocalization_P.ucas" />
    <None Remove="playAssets\2026\patch\BodycamLocalization_P.utoc" />
    <None Remove="wpfui-icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\app.ico" />
    <Resource Include="Assets\bodycambackg.jpg" />
    <Resource Include="Assets\bodycamsteam.jpg" />
    <Resource Include="Assets\wpfui-icon-256.png" />
    <Resource Include="Assets\wpfui-icon-1024.png" />
    <EmbeddedResource Include="playAssets\2025\BodycamLocalization_P.ucas">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="playAssets\2026\AruiAndmetaOBS\BodycamLocalization_P.pak">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="playAssets\2026\BodycamLocalization_P.ucas">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="playAssets\2026\patch\BodycamLocalization_P.pak" />
    <EmbeddedResource Include="playAssets\2026\patch\BodycamLocalization_P.ucas" />
    <EmbeddedResource Include="playAssets\2026\patch\BodycamLocalization_P.utoc" />
  </ItemGroup>

</Project>
